version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci(deps)"

  # npm (test host)
  - package-ecosystem: npm
    directory: /tests/e2e/test_host
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  # Python
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
    commit-message:
      prefix: "chore(deps)"
